# Searching services
- name: DUCKDUCKGO
  shortcut: d
  uri: https://duckduckgo.com/?q=%s
- name: GOOGLE
  shortcut: g
  uri: https://google.com/search?q=%s
- name: STACKOVERFLOW
  shortcut: so
  uri: https://duckduckgo.com/?q=%s site:stackoverflow.com
- name: NEOVIMCRAFT
  shortcut: vp
  uri: https://neovimcraft.com/?search=%s
- name: MY_GITHUB_ME
  shortcut: ghme
  uri: https://github.com/bedware/%s
- name: MY_GITHUB_STARS
  shortcut: ghs
  uri: https://github.com/bedware?q=%s&tab=stars
- name: MY_GITHUB_REPOS
  shortcut: ghr
  uri: https://github.com/bedware?tab=repositories&q=%s
# Apps
- name: INFOMATE
  shortcut: news
  uri: https://infomate.club/
- name: AI_LIBRARY
  shortcut: ailib
  uri: https://library.phygital.plus/
- name: EXCALIDRAW
  shortcut: draw
  uri: https://excalidraw.com/
- name: BING
  shortcut: bing
  uri: https://www.bing.com/search?q=Bing+AI&showconv=1
- name: DEEL
  shortcut: deel
  uri: https://app.deel.com
- name: GOOGLE_SHEETS
  shortcut: sheets
  uri: https://docs.google.com/spreadsheets/
- name: GOOGLE_DOCUMENTS
  shortcut: docs
  uri: https://docs.google.com/document/
